### ISSUE TITLE
FR13. Administrative Rights

### ISSUE THREAD

**Issue by TooAnonymous** [UNO-CSCI4830/JumpStart#12]
|FR13. Administrative Rights|
|---|
|**Goal**: Website Administrators will be able to delete user accounts.|
**Stakeholders:** All|
| **Description:** Administrators can delete accounts for the purposes of keeping the website safe and from others misusing the website.|
| **Origin:** Based on project specification document, team members came up with this description during the second meeting.|
| **Version:** 1.0 |
|**Date:** 10/01/2024
| **Priority:** 3 |

**Comment by Jocelyn-Hn** [comment]
Administrators have the ability to delete user accounts.
