### ISSUE TITLE
FR6. New Posts & Advice

### ISSUE THREAD

**Issue by Olay02** [UNO-CSCI4830/JumpStart#14]
|FR6. New Posts & Advice|
|---|
|**Goal**: Users will be able to submit new posts and advice. |
**Stakeholders:** All|
| **Description:** Allow users to submit new posts and advice if they want to share any of their experiences for other users to see. |
| **Origin:** First meeting.|
| **Version:** 1.0 |
|**Date:** 09/13/2024
| **Priority:** 1 |

**Comment by djseth-81** [comment]
Users can submit posts that will sit in a special database to be reviewed by an administrator
