### ISSUE TITLE
NFR3. Multiple Users

### ISSUE THREAD

**Issue by TooAnonymous** [UNO-CSCI4830/JumpStart#16]
|NFR3. Multiple Users|
|---|
|**Goal**: Website should allow multiple users to access it simultaneously.|
**Stakeholders:** All|
| **Description:** Be able to support multiple people on the website simultaneously. Allowing users to comment and interact with each other in real-time.|
| **Origin:** Based on project specification document, team members came up with this description during the second meeting.|
| **Version:** 1.0 |
|**Date:** 10/01/2024
| **Priority:** 2 |

**Comment by djseth-81** [comment]
Original intent was to be functional for multiple users to access simultaneously. Have fulfilled this goal.
