### ISSUE TITLE
NFR2. Website Compatability

### ISSUE THREAD

**Issue by ztrfi** [UNO-CSCI4830/JumpStart#17]
|NFR2.  Website Compatability|
|---|
|**Goal**:  Website should be accessible from all modern web browsers.
**Stakeholders:** Users|
| **Description:** The website requires users to have an active internet connection to access its features and content. Ensuring consistent availability and accessibility is critical to providing a seamless user experience. The website should also be able to run on multiple modern browsers. Ex. Chrome, Firefox, Safari, etc. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 10/01/2024
|  **Priority:** 2 |

**Comment by djseth-81** [comment]
Confirmed inter-browser operability
