### ISSUE TITLE
FR9. Advice Submission Approval Process

### ISSUE THREAD

**Issue by Jocelyn-Hn** [UNO-CSCI4830/JumpStart#18]
|FR9. Advice Submission Approval Process|
|---|
|**Goal**: Advice submitted by users will go through an approval process before being published on the website.
**Stakeholders:** All|
| **Description:** This process ensures that all advice content is reviewed and approved by administrators before being made public on the website. This also ensures that all advice being made public on the website is appropriate and suitable to be viewed. The system must implement an approval process for advice submitted by users. 
| **Origin:** Based on project specification document, team members came up with this description during the second meeting.|
| **Version:** 1.0 |
|**Date:** 10/01/2024
| **Priority:** 2 |

**Comment by djseth-81** [comment]
Advice will sit in a database pending administrator approval. They can be edited, rejected, or accepted and then published publicly
