### ISSUE TITLE
FR2. Submit New Resource

### ISSUE THREAD

**Issue by Olay02** [UNO-CSCI4830/JumpStart#2]
|FR2. Submit New Resource|
|---|
|**Goal**: Users will be able to submit new student resources to the website. |
**Stakeholders:** All|
| **Description:** Users will be able to submit a new resource that has to include at least a title and a brief description of what the resource is. Users can also link an external link to learn more about the resource if applicable. |
| **Origin:** First meeting|
| **Version:** 1.0 |
|**Date:** 09/13/2024
| **Priority:** 3 |

**Comment by djseth-81** [comment]
Submissions will be moved to a collection for review by administratord
