### ISSUE TITLE
NFR5. Code Organized & Documented

### ISSUE THREAD

**Issue by Olay02** [UNO-CSCI4830/JumpStart#20]
|NFR5. Code Organized & Document|
|---|
|**Goal**: Codebase should be organized and well documented |
**Stakeholders:** All |
| **Description:** All code should be well documented and organized for clear understanding for readers and other developers. |
| **Origin:** First Meeting.|
| **Version:** 1.0 |
|**Date:** 09/13/2024
| **Priority:** 1 |

**Comment by Jocelyn-Hn** [comment]
Sprint/Scrum meeting notes need to be added to the Wiki before final submission. Wiki pages kept up to date as more front/back end changes are being made.

**Comment by ESquaredProgramming** [comment]
Code is overall well-organized and commented.

**Comment by ESquaredProgramming** [comment]
Code is overall well-organized and documented.
