### ISSUE TITLE
FR10. User Navigation

### ISSUE THREAD

**Issue by TooAnonymous** [UNO-CSCI4830/JumpStart#4]
|FR10. User Navigation|
|---|
|**Goal**: Users will be able to navigate through the website via links and buttons. |
**Stakeholders:** All|
| **Description:** Website will have a user-friendly UI, allowing users to easily navigate through the various pages and resources in the website. |
| **Origin:** Based on project specification document, team members came up with this description during the second meeting.|
| **Version:** 1.0 |
|**Date:** 10/01/2024
| **Priority:** 1 |

**Comment by djseth-81** [comment]
Event cards redirect user to UNO page, and React elements can navigate between one another. User provided links can redirect as well
