### ISSUE TITLE
FR11. Account verification

### ISSUE THREAD

**Issue by TooAnonymous** [UNO-CSCI4830/JumpStart#5]
|FR11. User account verification |
|---|
|**Goal**: Users will be able to verify their accounts for security. |
**Stakeholders:** All|
| **Description:** User accounts will be verified when submitting posts and student resources to the website. |
| **Origin:** Based on project specification document, team members came up with this description during the second meeting.|
| **Version:** 1.0 |
|**Date:** 10/01/2024
| **Priority:** 2 |

**Comment by Jocelyn-Hn** [comment]
Users are required to verify their accounts using their school email. Their email is used when submitting posts and resources to the website.
