### ISSUE TITLE
FR12. Login Page

### ISSUE THREAD

**Issue by TooAnonymous** [UNO-CSCI4830/JumpStart#6]
|FR12. Login Page|
|---|
|**Goal**: Users will be able to log into their accounts through a login page. |
**Stakeholders:** All |
| **Description:** Users will be able to log into their accounts through the login page from any device.|
| **Origin:** Based on project specification document, team members came up with this description during the second meeting.|
| **Version:** 1.0 |
|**Date:** 10/01/2024
| **Priority:** 2 |

**Comment by Jocelyn-Hn** [comment]
Currently, we have a verification page that prompts the user for their school email and a verification code.

**Comment by ESquaredProgramming** [comment]
Currently, there is not a separate page, but a popup on the website that provides the same purpose.
