### ISSUE TITLE
FR5. Tracking Relevance

### ISSUE THREAD

**Issue by Olay02** [UNO-CSCI4830/JumpStart#7]
|FR5. Tracking Relevance |
|---|
|**Goal**: The Website will track the relevance of posts to provide the most relevant advice .|
**Stakeholders:** All|
| **Description:** Implement a system that tracks the relevance of posts and stores this data in the database. This will enable the platform to showcase tailored posts depending on the users interested. Such as Most Liked, Disliked, or Most Recent.|
| **Origin:** First meeting.|
| **Version:** 1.0 |
|**Date:** 09/13/2024 | 
| **Priority:** 2 |

**Comment by djseth-81** [comment]
User can sort by most popular if desired wanted. We also show upcoming UNO events
